### ISSUE TITLE
Struct namespaces erroneously delimited with '#'

### ISSUE THREAD

**Issue by NidusUmbra** [Orvid/Champollion#11]
Decompiled scripts containing structs will have ':' replaced by '#' in namespace-delims. Attaching pic.
[2023-01-21 12 03 29](https://user-images.githubusercontent.com/85224917/213864164-779945f8-eeb1-4f09-8a6c-8dbdf42f31f9.png)

**Comment by nikitalita** [comment]
yes, I've run into this too; will take a look.

**Comment by nikitalita** [comment]
When the build action is done, can you try the artifact here to see if this fixes your issue? https://github.com/Orvid/Champollion/actions/runs/4028783002
