### ISSUE TITLE
Champollion not decompiling floats correctly.

### ISSUE THREAD

**Issue by Michael-wigontherun** [Orvid/Champollion#13]
Posted on Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/75248?tab=bugs&BH=0

> I observed the new Champollion that you added isn't decompiling floats correctly on my end. They are decompiled as integers in the scripts and throw errors soon after in the process as the papyrus compiler tries to build.
> 
> I fixed it by switching out the Champollion with another in nexus. Namely this one: https://www.nexusmods.com/skyrim/mods/35307
> 
> EDIT: I couldnt obtain the error output because the compiler never crashes and indefinitely hangs accumulating memory in the background.

**Comment by nikitalita** [comment]
Don’t copy and paste nexus screenshots as issues, please.

**Comment by Michael-wigontherun** [comment]
It was in my ESLify Everything bugs section.

**Comment by nikitalita** [comment]
Sure, but don't post a screenshot. Post a link to the message and copy and paste the contents.

**Comment by nikitalita** [comment]
I updated your post. The reason why I need links to the original post is because without them, context is often lost, and I also can't contact the original poster to ask for more details. In the future, I suggest just letting people know that they have to submit the issue here.

**Comment by marqgray** [comment]
I'm the original poster with this error, and others may be getting a similar error on some mods. I used the "ESLify Everything" tool to decompile scripts using this Champollion tool, but floats, strings, and other things were not decompiled correctly. I don't know if this is specific mod related, but I have yet to try it on other mods. 

I did some Google searching around and found other posters years in the past having problems decompiling SexLab mods, so if this gets fixed, then this may be the first one that can efficiently handle it. I used an old Champollion tool on Skyrim Nexus that had a last update back in 2018 that managed to get past the problem, but I also read for some mods it can cause issues with what it exports in the decompiled scripts, so I'd rather not depend on it.

Here is a pastebin command-line output of the issue when the decompiled script is run through the papyrus compiler:
https://pastebin.com/zd9bCnYm

The mod in question that was the isolated target: https://www.loverslab.com/files/file/13464-furniture-sex-framework/

The following mods are its dependencies:

https://www.nexusmods.com/skyrimspecialedition/mods/12604/?tab=forum&topic_id=6328036
https://www.nexusmods.com/skyrimspecialedition/mods/3038?tab=files
https://www.loverslab.com/files/file/20058-sexlab-se-sex-animation-framework-v165-110822/

For your reference, I made a step-by-step video that gives a detailed visual of how exactly I reproduced the errors. https://youtu.be/I66DdjcikSg

I'd be happy to provide more information.

**Comment by nikitalita** [comment]
excellent, thank you for the detailed post. 
> I used an old Champollion tool on Skyrim Nexus that had a last update back in 2018 that managed to get past the problem, but I also read for some mods it can cause issues with what it exports in the decompiled scripts, so I'd rather not depend on it.

Your original post says you used [this Champollion at Nexus](https://www.nexusmods.com/skyrim/mods/35307), is this correct?

**Comment by marqgray** [comment]
> excellent, thank you for the detailed post.
> 
> > I used an old Champollion tool on Skyrim Nexus that had a last update back in 2018 that managed to get past the problem, but I also read for some mods it can cause issues with what it exports in the decompiled scripts, so I'd rather not depend on it.
> 
> Your original post says you used [this Champollion at Nexus](https://www.nexusmods.com/skyrim/mods/35307), is this correct?

Oops, that's from 2013, but yes, that's the correct one I used.

**Comment by nikitalita** [comment]
When the build action is done here, can you give the artifact here a try and see if this fixes the issue? https://github.com/Orvid/Champollion/actions/runs/4034651987

**Comment by marqgray** [comment]
The floats have been fixed. They are no longer an issue! I still get the other errors preventing successful compilation, but the floats are taken care of.

**Comment by nikitalita** [comment]
> The floats have been fixed. They are no longer an issue! I still get the other errors preventing successful compilation, but the floats are taken care of.

what are the other errors? IF they have anything to do with decompilation, can you please make another issue?
