### ISSUE TITLE
Failing for compiling Papyrus script using ELSifyEverything

### ISSUE THREAD

**Issue by jsbrando** [Orvid/Champollion#15]
Here's a manual list of issues I'm seeing when trying to recompile with the tool.

(base) PS E:\> cd '.\SteamLibrary\steamapps\common\Skyrim Special Edition\Papyrus Compiler\'
(base) PS E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Papyrus Compiler> .\PapyrusCompiler.exe "D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ChangedScripts" -q -f="TESV_Papyrus_Flags.flg" -a -i="D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts" -o="F:\Skyrim Special Edition - Latest Build\mods\ESLify Everything - Outputs\Scripts"
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\SKI_ConfigBase.psc(10,30): no viable alternative at input '_currentPage'
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\SKI_ConfigBase.psc(14,32): no viable alternative at input '_textBuf'
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\SKI_ConfigBase.psc(14,41): required (...)+ loop did not match anything at input 'AutoReadOnly'
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\SKI_ConfigBase.psc(14,9): Unknown user flag _textBuf
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(642,15): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(691,7): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(692,7): UnregisterForAnimationEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(697,9): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(701,9): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(705,9): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(709,9): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(713,9): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1322,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1323,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1324,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1325,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1326,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1328,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1331,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1334,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1337,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1340,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1408,7): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1538,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1539,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1540,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1541,7): UnregisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1549,13): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1552,13): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1556,15): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1597,19): RegisterForSingleUpdate is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1601,19): RegisterForSingleUpdate is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1622,13): SendModEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1624,11): RegisterForAnimationEvent is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1639,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1642,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1645,9): RegisterForKey is not a function or does not exist
D:\Modding Tools\SSEEdit\SSEEdit 4.0.4\ESLifyEverything\ExtractedBSAModData\Source\Scripts\_snskyuiconfig.psc(1648,9): RegisterForKey is not a function or does not exist
No output generated for _sndlcquestscript.psc, compilation failed.

**Comment by nikitalita** [comment]
I can't tell from the names of the scripts which mods they belong to. Can you please post that info? I need the original mods if I'm going to be able to recreate the issue.

**Comment by jsbrando** [comment]
I know a couple of the mods were: 
[iNeed ](https://www.nexusmods.com/skyrimspecialedition/mods/19390?tab=files)
[Dangerous Diseases](https://www.nexusmods.com/skyrimspecialedition/mods/35430)
[Wet & Cold](https://www.nexusmods.com/skyrimspecialedition/mods/644)

I've had a few others, but don't recall which ones they were...

**Comment by nikitalita** [comment]
Can you please post the full modlist from your mod organizer or whatever?

**Comment by jsbrando** [comment]
[Work in progress](https://pastebin.com/BjCv1PKA)

**Comment by nikitalita** [comment]
bruh

**Comment by nikitalita** [comment]
Yeah, that's over 3000 lines long and not particularly useful. Just make sure that you're using the latest Champollion in the releases section.

**Comment by Michael-wigontherun** [comment]
Jsbrando do you use MO? If you do go to the data page and search for "Scripts_snskyuiconfig.pex" without the ", and report what mod it says it comes from.

**Comment by Michael-wigontherun** [comment]
With the link to the download page.

**Comment by jsbrando** [comment]
As you can see, that script you list isn't found.  The only script I find with 'skyuiconfig' as the last part is shown [here](https://imgur.com/aYdAI8m).

[Wet & Cold](https://www.nexusmods.com/skyrimspecialedition/mods/644)

**Comment by Michael-wigontherun** [comment]
At the bottom of that page, click to check mark the Archives, refresh MO2, then search for  "_sndlcquestscript.pex" and "_snskyuiconfig.pex" without the ". I think the console output may have not picked up the \ after scripts in the file path. Because that is where the source scripts are located.

**Comment by jsbrando** [comment]
Ah... gotcha.... I'd never given 'Archives' much thought since it wasn't able to be checked.  Found I had to enable the 'experimental'  feature in settings.  Here you go...
Only mod listed with that script: [iNeed - Food, Water and Sleep - Continued.](https://www.nexusmods.com/skyrimspecialedition/mods/19390?tab=files)  One of the ones I called out above.

**Comment by jsbrando** [comment]
@nikitalita let me know if you need further information or testing.  I'm motivated to help you resolve this bug.

**Comment by nikitalita** [comment]
Thanks for the additional info!

I think I've fixed the issue now; can you please give the artifacts here a try to see if this fixes the issue? 
https://github.com/Orvid/Champollion/actions/runs/4093567166

**Comment by jsbrando** [comment]
> 

Testing it now.

**Comment by jsbrando** [comment]
Nice!  That appears to have resolved this issue.  At least with that script from iNeed.  You can close this issue and if I run into another, I'll open a new bug and link this one to it for reference.
Thanks, @nikitalita & @Michael-wigontherun!
Cheers,
Jason
