### ISSUE TITLE
Invalid String Index

### ISSUE THREAD

**Issue by 0xDezzy** [Orvid/Champollion#21]
When trying to use Champollion to decompile a pex file from Starfield I'm getting an Invalid String Index error for every file.

**Comment by Orvid** [comment]
Which version of Champollion are you using? v1.1.3 will show this error when decompiling Starfield files. v1.2.2 is the only version that currently supports starfield: https://github.com/Orvid/Champollion/releases/tag/v1.2.2

**Comment by 0xDezzy** [comment]
Ah that'll do it. Thanks!
