### ISSUE TITLE
Fix Event tagging

### ISSUE THREAD

**Issue by nikitalita** [Orvid/Champollion#7]
We currently determine whether or not to flag events based on whether or not they start with "On". This can lead to non-event functions being tagged as events, such as "OnlyDoIf". We need to implement proper analysis on whether or not a function is an event for both skyrim and fallout4.

**Comment by Orvid** [comment]
If a better analysis is needed, it would be worth extending that to FO4's custom events, as they are not currently recorded anywhere in the pex, so you just have to find what places manually invoke the custom event and make sure to emit that event.

**Comment by nikitalita** [comment]
If they're not recorded anywhere in the pex, how can we tell what's a custom event?
